# Base de datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/tesla_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# Logs muy detallados
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Redis (local)
spring.data.redis.host=localhost
spring.data.redis.port=6379