spring.application.name=teslabackend

spring.profiles.active=dev

# Cloudinary Credentials
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Spring Boot Multipart File Configuration (Maximo 10MB por archivo)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# seguridad
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_luGtUNvSh}