spring.application.name=teslabackend

spring.profiles.active=dev

# AWS S3 & CloudFront Configuration
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.cloudfront.url=${AWS_CLOUDFRONT_URL}

# Spring Boot Multipart File Configuration (Maximo 10MB por archivo)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# seguridad
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI}