# Base de datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/tesla_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# Logs muy detallados
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO

# S3
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${S3_BUCKET_NAME:tesla-hub-storage-dev}
aws.s3.public-base-url=https://tesla-hub-storage-dev.s3.amazonaws.com
aws.s3.presigned-url-duration-minutes=10
aws.s3.allowed-content-types=image/jpeg,image/png,image/webp

# Redis (local)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

# MQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=61613
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest